### ISSUE TITLE
ADC Drivers

### ISSUE THREAD

**Issue by Jchisholm204** [qfsae/zenith#63]
# Issue
Current ADC Drivers are based on a blocking/polling basis.
# TODO
- Implement ADC Interrupts
- Figure out ADC Ques
- Figure out how to run RTOS tasks upon ADC measurements being finished (run APPS Plausibility checks)

**Comment by OgliariNatan** [comment]
I'm Brazilian and I'm interested in helping or learning together, I have experience in cam bus.
